//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class galleryEntities : DbContext
    {
        public galleryEntities()
            : base("name=galleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exhibits> Exhibits { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Moving> Moving { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
