//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_8.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetData(string date_start, string date_end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string date_start, string date_end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void NewRec(string exh_fk, string halls_fk, string date_start, string date_end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewRec", ReplyAction="*")]
        System.Threading.Tasks.Task NewRecAsync(string exh_fk, string halls_fk, string date_start, string date_end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteRec(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRec", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRecAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Show", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Show(string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Show", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAsync(string tableName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BIPIT_8.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BIPIT_8.ServiceReference1.ServiceSoap>, BIPIT_8.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetData(string date_start, string date_end) {
            return base.Channel.GetData(date_start, date_end);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string date_start, string date_end) {
            return base.Channel.GetDataAsync(date_start, date_end);
        }
        
        public void NewRec(string exh_fk, string halls_fk, string date_start, string date_end) {
            base.Channel.NewRec(exh_fk, halls_fk, date_start, date_end);
        }
        
        public System.Threading.Tasks.Task NewRecAsync(string exh_fk, string halls_fk, string date_start, string date_end) {
            return base.Channel.NewRecAsync(exh_fk, halls_fk, date_start, date_end);
        }
        
        public void DeleteRec(int id) {
            base.Channel.DeleteRec(id);
        }
        
        public System.Threading.Tasks.Task DeleteRecAsync(int id) {
            return base.Channel.DeleteRecAsync(id);
        }
        
        public System.Data.DataSet Show(string tableName) {
            return base.Channel.Show(tableName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAsync(string tableName) {
            return base.Channel.ShowAsync(tableName);
        }
    }
}
